name: test_task
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

  # state management
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5

  # dependency injection
  get_it: ^7.2.0
  injectable: ^2.1.1

  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  injectable_generator: ^2.1.5
  build_runner: ^2.3.3

flutter:

  uses-material-design: true

  assets:
    - assets/font/poppins/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/poppins/Poppins_Light.ttf
          weight: 300
        - asset: assets/font/poppins/Poppins_Regular.ttf
          weight: 400
        - asset: assets/font/poppins/Poppins_Medium.ttf
          weight: 500
        - asset: assets/font/poppins/Poppins_SemiBold.ttf
          weight: 600
        - asset: assets/font/poppins/Poppins_Bold.ttf
          weight: 700
        - asset: assets/font/poppins/Poppins_Black.ttf
          weight: 900